# Generated by Django 5.0.2 on 2025-03-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_alter_orderitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(null=True),
        ),
    ]
