# Generated by Django 5.0.2 on 2025-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_order_shipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
