# Generated by Django 5.0.2 on 2025-03-09 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="New_Product",
        ),
    ]
