# Generated by Django 5.0.2 on 2025-02-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, max_length=7
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("image", models.ImageField(upload_to="uploads/product/")),
                ("is_sale", models.BooleanField(default=False)),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pro.category",
                    ),
                ),
            ],
        ),
    ]
