# Generated by Django 5.0.2 on 2025-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="our_cart",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
