# Generated by Django 5.0.2 on 2025-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0006_profile_our_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="our_cart",
        ),
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
