# Generated by Django 5.0.2 on 2025-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0007_remove_profile_our_cart_profile_old_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_product",
            field=models.BooleanField(default=False),
        ),
    ]
