# Generated by Django 5.0.2 on 2025-03-09 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0008_product_new_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="new_product",
        ),
    ]
