# Generated by Django 5.0.2 on 2025-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0009_remove_product_new_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_product",
            field=models.BooleanField(default=False),
        ),
    ]
