# Generated by Django 5.0.2 on 2025-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0011_userquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="outof_stock",
            field=models.BooleanField(default=False),
        ),
    ]
