# Generated by Django 5.0.2 on 2025-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0014_shoesize"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(related_name="products", to="pro.shoesize"),
        ),
    ]
