# Generated by Django 5.0.2 on 2025-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0016_remove_product_sizes_delete_shoesize"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoeSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(related_name="products", to="pro.shoesize"),
        ),
    ]
