# Generated by Django 5.1.7 on 2025-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0017_shoesize_product_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoesize",
            name="size",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
