# Generated by Django 5.0.2 on 2025-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0018_alter_shoesize_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="pro.shoesize"
            ),
        ),
    ]
