# Generated by Django 5.0.2 on 2025-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0019_alter_product_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Trending_products",
            field=models.BooleanField(default=False),
        ),
    ]
