# Generated by Django 5.0.2 on 2025-03-24 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0020_product_trending_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="images",
        ),
    ]
