# Generated by Django 5.0.2 on 2025-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0021_rename_image_productimage_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
