# Generated by Django 5.0.2 on 2025-03-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pro", "0022_alter_profile_old_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="images",
            field=models.ImageField(upload_to="uploads/product/"),
        ),
    ]
